mod 'puppet/nginx', '3.2.0'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/translate'
mod 'samuelson/dockeragent'
mod 'puppetlabs/docker'
mod 'puppetlabs-apt', '8.0.2'
mod 'puppetlabs-powershell', '5.0.0'
mod 'puppetlabs-pwshlib', '0.10.0'
mod 'puppetlabs-reboot', '4.0.2'
